Improve warning output in `release-cancel`.
Signed-off-by: Ross Goldberg <484615+rgoldberg@users.noreply.github.com>

diff --git a/Scripts/release-cancel b/Scripts/release-cancel
--- a/Scripts/release-cancel
+++ b/Scripts/release-cancel
@@ -25,7 +25,7 @@ if [[ -n "${bump_url}" ]]; then
 	gh pr close "${bump_url}" -d
 	printf $'\n'
 else
-	printf $'\nNo tap formula bump PR URL found for draft release tag %s\n\n' "${tag}"
+	printf $'\nWarning: Failed to find tap formula bump PR URL for draft release tag %s\n\n' "${tag}" >&2
 fi
 
 gh release -R mas-cli/mas delete "${tag}" --cleanup-tag -y
